#include "windowrace.h"
#include <QApplication>
#include "measurement.h"
#include "windowraceuser.h"
#include "windowusart.h"
#include "windowusermain.h"
#include "windowracemain.h"
/*#include <QFile>
#include <QTextStream>*/

using namespace std;

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    WindowRaceMain w;
    w.show();


    /*QFile file("a.txt"); file.open(QIODevice::WriteOnly | QIODevice::Text);
    QTextStream out(&file);
    out << "This file is generated by Qt\n";
    file.close();*/


    return a.exec();
}
